kotlin.code.style=official
xcodeproj=./iosApp
android.useAndroidX=true

org.gradle.jvmargs=-Xmx2048M -Dkotlin.daemon.jvm.options\="-Xmx2048M"
kotlin.mpp.androidSourceSetLayoutVersion=2
android.nonTransitiveRClass=false
android.nonFinalResIds=false

# BuildConfig
buildConfig.debug=true
buildConfig.versionName=0.7.0
buildConfig.versionCode=33
