kotlin.code.style=official
xcodeproj=./iosApp
android.useAndroidX=true

org.gradle.jvmargs=-Xmx3g -Dkotlin.daemon.jvm.options\="-Xmx3g"
kotlin.mpp.androidSourceSetLayoutVersion=2
android.nonTransitiveRClass=false
android.nonFinalResIds=false
org.gradle.caching=true

# BuildConfig
buildConfig.debug=true
buildConfig.versionName=0.7.0
buildConfig.versionCode=33

#iOS
org.jetbrains.compose.experimental.uikit.enabled=true
kotlin.incremental.native=true
