# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'
use_frameworks!

def shared_pods
  pod 'ComposeApp', :path => '../composeApp'
  pod 'Sentry', '8.49.0'

end

target 'MoreStuff' do
    shared_pods

end

#target 'MoreStuffShare' do
#    shared_pods
#
#end
