[versions]
turbine = "1.0.0"
coilCompose = "3.1.0"
firebaseBom = "33.13.0"
googleServices = "4.4.2"
koinTest = "3.5.6"
workKtx = "2.10.1"
preferenceKtx = "1.2.1"
firebaseCrashlyticsPlugin = "3.0.3"
aboutLibrariesVersion = "11.2.1"
kSoup = "0.3.0"
sqliteAndroid = "3.45.0"

agp = "8.8.2"
kotlin = "2.1.0"

android_sdk_compile = "35"
android_sdk_target = "35"
android_sdk_min = "26"

androidx-core = "1.16.0"
kotlinx-immutable-collections = "0.3.7"
kotlinx-coroutines = "1.10.1"
kotlinx-serialization = "1.8.0"
kotlinx-datetime = "0.6.2"
kotlinx-atomicfu = "0.27.0"
compose = "1.7.3"
androidx-activity-compose = "1.10.1"
androidx-appcompat = "1.7.0"
androidx-test = "1.6.1"
androidx-lifecycle = "2.9.0"
kermit = "2.0.5"
ktor = "3.1.1"
multiplatform-settings = "1.3.0"
koin-bom = "4.1.0-Beta1"
sqldelight = "2.0.2"
arrow = "2.0.1"
buildConfig = "5.5.1"
spotless = "6.23.3"
ktfmt = "0.44"
stately = "2.0.6"
mockk-common = "1.12.5"
mockk = "1.13.8"
junit5 = "5.11.3"
junit-platform-commons = "1.11.3"
security-crypto = "1.0.0"
store5 = "5.0.0"
decompose-router = "0.9.0"
decompose = "3.2.2"
essenty = "2.0.0"
molecule = "2.0.0"
exifinterfaceVersion = "1.4.1"
constraintLayout-compose = "0.4.0"
compose-settings = "2.4.0"
sonner = "0.3.6"
reorderable = "2.4.3"
zoomable = "1.6.1"
kottie = "1.9.6-alpha02"
calf = "0.7.1"
filekit = "0.10.0-beta01"
supabase-bom = "3.1.3"
openAi = "4.0.1"


[libraries]
# Kotlin
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-immutable-collections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-immutable-collections" }
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlinx-atomicfu" }

# Compose
compose-ui-util = { module = "org.jetbrains.compose.ui:ui-util", version.ref = "compose" }

# Android
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "security-crypto" }
androidx-test = { module = "androidx.test:core", version.ref = "androidx-test" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "androidx-lifecycle" }

# Ktor
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }

# SqlDelight
sqldelight-driver-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-driver-native = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
sqldelight-driver-desktop = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
sqldelight-sqlite-dialect = { module = "app.cash.sqldelight:sqlite-3-35-dialect", version.ref = "sqldelight" }
sqldelight-coroutines-extensions = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
sqldelight-primitive-adapters = { module = "app.cash.sqldelight:primitive-adapters", version.ref = "sqldelight" }

# Koin
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android" }

# Supabase
supabase-bom = { module = "io.github.jan-tennert.supabase:bom", version.ref = "supabase-bom" }
supabase-postgres = { module = "io.github.jan-tennert.supabase:postgrest-kt" }
supabase-auth = { module = "io.github.jan-tennert.supabase:auth-kt" }
supabase-compose-auth = { module = "io.github.jan-tennert.supabase:compose-auth" }
supabase-compose-auth-ui = { module = "io.github.jan-tennert.supabase:compose-auth-ui" }

# Misc
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatform-settings" }
multiplatform-settings-test = { module = "com.russhwolf:multiplatform-settings-test", version.ref = "multiplatform-settings" }

arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
stately-isolate = { module = "co.touchlab:stately-isolate", version.ref = "stately" }
stately-iso-collections = { module = "co.touchlab:stately-iso-collections", version.ref = "stately" }
decompose-router = { module = "io.github.xxfast:decompose-router", version.ref = "decompose-router" }
decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-compose-multiplatform = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }
molecule-runtime = { module = "app.cash.molecule:molecule-runtime", version.ref = "molecule" }
composeSettings-ui = { group = "com.github.alorma.compose-settings", name = "ui-tiles", version.ref = "compose-settings" }
composeSettings-ui-extended = { group = "com.github.alorma.compose-settings", name = "ui-tiles-extended", version.ref = "compose-settings" }
settingsStoragePreferences = { group = "com.github.alorma.compose-settings", name = "storage-base", version.ref = "compose-settings" }
sonner = { module = "io.github.dokar3:sonner", version.ref = "sonner" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose-core", version.ref = "coilCompose" }
coil-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coilCompose" }
coil-ktor2 = { module = "io.coil-kt.coil3:coil-network-ktor2", version.ref = "coilCompose" }
zoomable = { module = "com.mxalbert.zoomable:zoomable", version.ref = "zoomable" }
kottie = { module = "io.github.ismai117:kottie", version.ref = "kottie" }
calf-permissions = { module = "com.mohamedrejeb.calf:calf-permissions", version.ref = "calf" }
calf-filepicker = { module = "com.mohamedrejeb.calf:calf-file-picker", version.ref = "calf" }
calf-filepicker-coil = { module = "com.mohamedrejeb.calf:calf-file-picker-coil", version.ref = "calf" }
calf-io = { module = "com.mohamedrejeb.calf:calf-io", version.ref = "calf" }

filekit-dialogs = { module = "io.github.vinceglb:filekit-dialogs", version.ref = "filekit" }
filekit-dialogs-compose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "filekit" }
filekit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "filekit" }
filekit-coil = { module = "io.github.vinceglb:filekit-coil", version.ref = "filekit" }
open-ai = { module = "com.aallam.openai:openai-client", version.ref = "openAi" }

# Testing
mockk-common = { module = "io.mockk:mockk-common", version.ref = "mockk-common" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit5" }
junit-platform-commons = { module = "org.junit.platform:junit-platform-commons", version.ref = "junit-platform-commons" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

# OLD

aboutLibrariesCore = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutLibrariesVersion" }
aboutLibrariesCompose = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutLibrariesVersion" }
preferenceKtx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }

firebaseBom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebaseCrashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebaseAnalytics = { module = "com.google.firebase:firebase-analytics-ktx" }
googleServices = { module = "com.google.gms:google-services", version.ref = "googleServices" }
koinTest = { module = "io.insert-koin:koin-test", version.ref = "koinTest" }
koinTestJunit = { module = "io.insert-koin:koin-test-junit5", version.ref = "koinTest" }
workKtx = { module = "androidx.work:work-runtime-ktx", version.ref = "workKtx" }
kSoup = { module = "com.mohamedrejeb.ksoup:ksoup-html", version.ref = "kSoup" }
constraintLayout-compose = { module = "tech.annexflow.compose:constraintlayout-compose-multiplatform", version.ref = "constraintLayout-compose" }
sqliteAndroid = { module = "com.github.requery:sqlite-android", version.ref = "sqliteAndroid" }
androidx-exifinterface = { group = "androidx.exifinterface", name = "exifinterface", version.ref = "exifinterfaceVersion" }

# END OLD

[plugins]
googleServicesPlugin = { id = "com.google.gms.google-services", version.ref = "googleServices" }
crashlyticsPlugin = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }
aboutLibrariesPlugin = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLibrariesVersion" }

android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildConfig" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[bundles]

kotlinx = ["kotlinx-coroutines", "kotlinx-datetime", "kotlinx-immutable-collections", "kotlinx-serialization-json", "kotlinx-atomicfu"]
