name: Create Staging Release

on:
  push:
    branches: [ "staging/**" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      GOOGLE_SERVER_CLIENT_ID: ${{ secrets.GOOGLE_SERVER_CLIENT_ID }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}

    steps:
      - uses: actions/checkout@v3

      - name: JDK setup
        uses: actions/setup-java@v3
        with:
          java-version: 20
          distribution: corretto
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Assemble Staging Bundle
        run: |
          ./gradlew :androidApp:assembleStaging

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{secrets.STAGING_FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_APP_DISTRIBUTION_CREDENTIALS }}
          groups: staging
          file: androidApp/build/outputs/apk/staging/androidApp-staging.apk