name: Test
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: JDK setup
        uses: actions/setup-java@v3
        with:
          java-version: 20
          distribution: corretto
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Execute unit tests
      - name: Unit Test
        run: ./gradlew testDebugUnitTest